---
title: "p8106_mtp_rq2166"
author: "Ruoyuan Qian"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(ggplot2)
devtools::install_github("thomasp85/patchwork")
library(Rmisc)
library(corrplot)
library(FNN)
```

Data cleaning
```{r}

house = read.csv(file = "train.csv")
#skimr::skim(house)

sum_na = function(x){
  sum = sum(is.na(x))
  sum}

# names of predictor when its missing value larger than 500
missing_var = map(house,sum_na) %>% 
  as.data.frame() %>% 
  pivot_longer(
    Id : SalePrice,
    names_to = "variable",
    values_to = "value"
  ) %>% 
  filter(value > 500 ) %>% 
  pull(variable) 

#house %>% 
#select(-Alley,-FireplaceQu,-PoolQC,-Fence,-MiscFeature) %>% 
#map(.,sum_na)
# names of variables when its value nears zero
near_0_var = 
  house %>% 
  nearZeroVar( names = TRUE)
  
final_house = 
  house %>% 
  #nearZeroVar( names = TRUE)
  select(-near_0_var,-missing_var,-Id) %>% 
  #select(-Alley,-FireplaceQu,-PoolQC,-Fence,-MiscFeature) %>% 
  drop_na()
```

Visualization

The response `SalePrice` is right skewed
```{r,fig.height=4}
density_sale = 
ggplot(final_house, aes(x = SalePrice, ..density..)) +
  geom_histogram(binwidth = 8000) +
  geom_line(stat = 'density',size = 0.7,color = "blue")+
  ggtitle("Figure 1 Density of SalePrice") +
  #ylab("Houses") +
  xlab("SalePrice") + 
  theme(plot.title = element_text(hjust = 0.5))

density_sale
```


```{r,fig.height=15,fig.width=15}
numeric_var_index = 
 final_house%>% 
  map(.,is.numeric) %>% 
  unlist() %>% 
  as.vector()

x <- model.matrix(SalePrice~.,
                  final_house[,which(numeric_var_index == TRUE)])[,-1]
y <- final_house$SalePrice


theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .5)
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1)
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)
featurePlot(x, y, plot = "scatter", labels = c("","Y"),
            type = c("p"), layout = c(7, 4))


```



```{r,fig.height=50,fig.width=40}

variable_name = names(final_house %>% 
  select(which(numeric_var_index == FALSE)))

dataframe = 
  final_house %>% 
  select(which(numeric_var_index == FALSE))
plots = function(dataframe){
variable_name = names(dataframe)

summary = 
final_house %>% 
  select(which(numeric_var_index == FALSE)) %>% 
  pivot_longer(
   everything(),
   names_to = "variable",
   values_to = "category"
  ) %>% 
  group_by(variable,category)%>% 
  count() %>% 
  mutate(n = freq) %>% 
  select(-freq)

plot_tem = 
  summary %>% 
  filter(variable == variable_name) %>% 
  ggplot(mapping = aes(x = category, 
                       y = n,fill = category)) + 
   geom_bar(stat = 'identity',position = 'dodge') +
 scale_fill_hue(c = 80)+
 ggtitle(paste("Bar plot of",variable_name))+
  labs(x = variable_name) +
 theme(plot.title = element_text(hjust = 0.5),
       legend.position="right")
    #plots = paste(plots,plot_tem,"+")
plot_tem
  }


plot_name = NULL
for(i in 1: length(dataframe)){
  plot_name_tem = paste("plots(dataframe %>% select(",i,"))",",")
  plot_name = c(plot_name,plot_name_tem)
}

#as.factor(plot_name)

multiplot( 
 plots(dataframe %>% select( 1 )) , 
plots(dataframe %>% select( 2 )) , 
plots(dataframe %>% select( 3 )) , 
plots(dataframe %>% select( 4 )) , 
plots(dataframe %>% select( 5 )) , 
plots(dataframe %>% select( 6 )) , 
plots(dataframe %>% select( 7 )) , 
plots(dataframe %>% select( 8 )) , 
plots(dataframe %>% select( 9 )) , 
plots(dataframe %>% select( 10 )) ,
plots(dataframe %>% select( 11 )) ,
plots(dataframe %>% select( 12 )) ,
plots(dataframe %>% select( 13 )) ,
plots(dataframe %>% select( 14 )) ,
plots(dataframe %>% select( 15 )) ,
plots(dataframe %>% select( 16 )) ,
plots(dataframe %>% select( 17 )) ,
plots(dataframe %>% select( 18 )) ,
plots(dataframe %>% select( 19 )) ,
plots(dataframe %>% select( 20 )) ,
plots(dataframe %>% select( 21 )) ,
plots(dataframe %>% select( 22 )) ,
plots(dataframe %>% select( 23 )) ,
plots(dataframe %>% select( 24 )) ,
plots(dataframe %>% select( 25 )) ,
plots(dataframe %>% select( 26 )) ,
          cols=4) 

```

heat map
```{r,fig.height=15,fig.width=15}
M<-cor(final_house[,which(numeric_var_index == TRUE)])

#corrplot(M,title = "Correlation Plot", method = "square", addgrid.col = "darkgray", order="hclust", mar = c(4,0,4,0), addrect = 5, rect.col = "black", rect.lwd = 5,cl.pos = "b", tl.col = "indianred4", tl.cex = 1.5, cl.cex = 1.5,addCoef.col = "black", number.digits = 2, number.cex = 0.75)

corrplot(M,title = "Correlation Plot", method = "square", addgrid.col = "darkgray", order="hclust", mar = c(4,0,4,0), addrect = 5, rect.col = "black", rect.lwd = 5,cl.pos = "b", tl.col = "indianred4", tl.cex = 1.5, cl.cex = 1.5)

```


```{r}

reg_data = as.data.frame(map(final_house,as.numeric))

x <- model.matrix(SalePrice~.,reg_data)[,-1]
y <- reg_data$SalePrice

ctrl1 <- trainControl(method = "repeatedcv", number = 10, repeats = 5)

```


Multiple linear regression

```{r}
set.seed(1)
lm.fit <- train(x, y,
                method = "lm",
                trControl = ctrl1,
                preProcess = c("center", "scale"))

tibble("MSE" = lm.fit $ results $ RMSE)%>% 
knitr::kable() 
```

K-nn
```{r}
set.seed(1)
knnFit <- train(x, y,
                method = "knn", 
                trControl = ctrl1,
                preProcess = c("center", "scale"),
                tuneLength = 20)
               #  tuneGrid = tibble(n = 7:10))


as.data.frame(knnFit$ results ) %>% 
  select(k,RMSE) %>% 
  filter(RMSE == min(RMSE)) %>% 
  knitr::kable() 
```

LASSO
```{r}
set.seed(1)
lasso.fit <- train(x, y,
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 1, 
                                          lambda = exp(seq(5,8, length=200))),
                   preProc = c("center", "scale"),
                   trControl = ctrl1)

plot(lasso.fit, xTrans = function(x) log(x))

```

```{r}

coe = coef(lasso.fit$finalModel,lasso.fit$bestTune$lambda)

as.data.frame(lasso.fit$ results ) %>% 
  select(lambda,RMSE) %>% 
  filter(RMSE == min(RMSE)) %>% 
  mutate("Number of non-zero coefficient" = length(which(coe[-1] != 0))) %>% 
  knitr::kable() 

```

Ridge
```{r}
set.seed(1)
ridge.fit <- train(x, y,
                   method = "glmnet",
                   tuneGrid = expand.grid(alpha = 0, 
                                          lambda = exp(seq(9, 12, length=200))),
                   preProc = c("center", "scale"),
                   trControl = ctrl1)


plot(ridge.fit, xTrans = function(x) log(x))
```

```{r}

as.data.frame(ridge.fit$ results ) %>% 
  select(lambda,RMSE) %>% 
  filter(RMSE == min(RMSE)) %>% 
  knitr::kable() 

```

Elastic
```{r}
set.seed(1)
enet.fit <- train(x, y,
                  method = "glmnet",
                  tuneGrid = 
                    expand.grid(alpha = seq(0, 1, length = 15), 
                                lambda = exp(seq(9,11, length = 50))),
                  preProc = c("center", "scale"),
                  trControl = ctrl1)
enet.fit$bestTune

ggplot(enet.fit, highlight = TRUE) +
  theme(legend.position="bottom")
```
```{r}
as.data.frame(enet.fit$ results ) %>% 
  select(lambda,RMSE) %>% 
  filter(RMSE == min(RMSE)) %>% 
  knitr::kable() 
```


PCA
```{r}
set.seed(1)

pcr.fit <- train(x, y,
                  method = "pcr",
                  tuneGrid = data.frame(ncomp = 1:54),
                  trControl = ctrl1,
                  scale = TRUE)

as.data.frame(pcr.fit$ results ) %>% 
  select(ncomp,RMSE) %>% 
  filter(RMSE == min(RMSE)) %>%
  knitr::kable() 

ggplot(pcr.fit, highlight = TRUE) + theme_bw()
```

PLS
```{r}
set.seed(1)

pls.fit <- train(x, y,
                  method = "pls",
                  tuneGrid = data.frame(ncomp = 1:54),
                  trControl = ctrl1,
                  scale = TRUE)

as.data.frame(pls.fit$ results ) %>% 
  select(ncomp,RMSE) %>% 
  filter(RMSE == min(RMSE)) %>%
  knitr::kable() 

ggplot(pls.fit, highlight = TRUE) + theme_bw()
```

```{r}
resamp <- resamples(list(lm = lm.fit,
                         lasso = lasso.fit, 
                         ridge = ridge.fit,
                         elastic = enet.fit,
                         pcr = pcr.fit, 
                         pls = pls.fit))
summary(resamp)

bwplot(resamp, metric = "RMSE")
```

So elastic is the best with smallest MSE.